blank_issues_enabled: true
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/CN7021-Group-Project/E-voting/blob/main/README.md
    about: Please check the documentation before creating an issue
  - name: ðŸ’¬ Discussions
    url: https://github.com/CN7021-Group-Project/E-voting/discussions
    about: Use GitHub Discussions for questions and general discussions
